New issue template for CRM updates
cal-itp/crm-helpdesk pull request #142
Opened 2022-09-21 22:30 UTC by AnthonyRollins

2022-09-21 22:31 UTC, AnthonyRollins commented
@thekaveman, Let me know if this looks good, but also if there was anything I should have done differently about creating a PR.

2022-09-21 23:00 UTC, thekaveman requested changes
Your PR looks good! I saw one minor thing to change

2022-09-21 23:00 UTC, thekaveman commented on .github/ISSUE_TEMPLATE/crm-record-update.yml
> +title: "[Deals Pipeline Request]: "
I think you'll want to update the `title` here

2022-09-21 23:00 UTC, thekaveman commented on .github/ISSUE_TEMPLATE/crm-record-update.yml
> +       ### Due to sensitive information, please submit your crm record request through Hubspot's Service Desk pipeline; [Internal Support](https://app.hubspot.com/contacts/5519226/objects/0-5/views/a
Nice! 👍

2022-09-22 17:52 UTC, AnthonyRollins commented
Made all changes

2022-09-23 17:02 UTC, thekaveman approved these changes
Looks great!

Just be sure to create the `crm-update` label before anyone uses this template.

2022-09-23 21:38 UTC, merged